project_id = "kgcnuucwqfasubtnqqmp"

[functions]
  [functions.admin-action]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-admin]
    verify_jwt = false
  [functions.crypto-callback]
    verify_jwt = false
  [functions.crypto-deposit]
    verify_jwt = false
  [functions.fetch-odds]
    verify_jwt = false
  [functions.mpesa-callback]
    verify_jwt = false
  [functions.mpesa-deposit]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
